version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies"
      - chmod +x ./gradlew

  pre_build:
    commands:
      - echo "Cleaning previous builds..."
      - ./gradlew clean

  build:
    commands:
      - echo "Building Android debug APK..."
      - ./gradlew assembleDebug

      - echo "Packaging Appium tests..."
      - cd appium
      - chmod +x packageTest.sh
      - ./packageTest.sh
      - cd ..

  post_build:
    commands:
      - echo "Verifying APK output..."
      - find ./app/build/outputs -name "*.apk" || (echo "APK not found!" && exit 1)

artifacts:
  files:
    - 'app/build/outputs/**/*.apk'
    - 'appium/target/**/*.zip'
  base-directory: .
  discard-paths: no
