version: 0.2

env:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx2g"
    _JAVA_OPTIONS: "-Xmx2g"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - set -e
      - echo "=== Installing Gradle 7.6.1 ==="
      - |
        curl -fsSL https://services.gradle.org/distributions/gradle-7.6.1-bin.zip -o gradle.zip
        unzip -q gradle.zip
        export PATH="$PWD/gradle-7.6.1/bin:$PATH"
        gradle --version

      - echo "=== Installing Android SDK CLI tools ==="
      - export ANDROID_SDK_ROOT="$HOME/android-sdk"
      - mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
      - curl -fsSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
      - unzip -q cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
      - mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
      - export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
      - chmod +x "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
      - sdkmanager --version || { echo "❌ sdkmanager missing"; exit 1; }

      - echo "=== Accepting licenses and installing SDK packages ==="
      - yes | sdkmanager --licenses >/dev/null
      - sdkmanager "platform-tools" "platforms;android-29" "build-tools;33.0.2"

      - chmod +x ./gradlew

  pre_build:
    commands:
      - echo "=== Gradle clean ==="
      - ./gradlew clean --stacktrace --info

  build:
    commands:
      - echo "=== Gradle assemble ==="
      - ./gradlew assembleDebug assembleAndroidTest --stacktrace --info

  post_build:
    commands:
      - echo "=== APKs generated ==="
      - find app/build/outputs -name "*.apk" -print
      - |
        if [ $(find app/build/outputs -name "*.apk" | wc -l) -eq 0 ]; then
          echo "❌ No APKs produced – failing build"; exit 1; fi

artifacts:
  discard-paths: yes
  files:
    - app/build/outputs/**/*.apk

cache:
  paths:
    - '/root/.gradle/**/*'
    - '$HOME/android-sdk/**/*'
