version: 0.2

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
      - cd test
      - npm install
      - npm install -g npm-bundle
      - npm-bundle
      - zip -r MyTest.zip *.tgz
artifacts:
  files:
     - './app/build/outputs/**/*.apk'
     - './appium/target/**/*.zip'
  discard-paths: yes