version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies"
      - chmod +x ./gradlew

  pre_build:
    commands:
      - echo "Cleaning project"
      - ./gradlew clean --stacktrace --info

  build:
    commands:
      - echo "Building APK"
      - ./gradlew assembleDebug --stacktrace --info

  post_build:
    commands:
      - echo "Listing generated APK"
      - find app/build/outputs -name "*.apk"

artifacts:
  files:
    - app/build/outputs/**/*.apk
