version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "=== Installing Android SDK and tools ==="
      - export ANDROID_SDK_ROOT=$HOME/android-sdk
      - mkdir -p $ANDROID_SDK_ROOT
      - curl -s https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -o cmdline-tools.zip
      - unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools-temp
      - mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
      - mv $ANDROID_SDK_ROOT/cmdline-tools-temp/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
      - export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
      - yes | sdkmanager --licenses
      - sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
      - echo "=== Android SDK setup complete ==="
      - chmod +x ./gradlew

  pre_build:
    commands:
      - echo "=== Cleaning project ==="
      - ./gradlew clean --stacktrace --info

  build:
    commands:
      - echo "=== Building APK and test APK ==="
      - ./gradlew assembleDebug assembleAndroidTest --stacktrace --info

  post_build:
    commands:
      - echo "=== Listing generated APKs ==="
      - find app/build/outputs -name "*.apk"

artifacts:
  files:
    - app/build/outputs/**/*.apk
