version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8  # ✅ Java 8 for compatibility with AGP 2.3.2
    commands:
      - echo "=== Installing Gradle 3.5 ==="
      - curl -s https://services.gradle.org/distributions/gradle-3.5-bin.zip -o gradle.zip
      - unzip -q gradle.zip
      - export PATH=$PWD/gradle-3.5/bin:$PATH

      - echo "=== Installing Android SDK (Build Tools 26.0.2 + Platform 22) ==="
      - export ANDROID_SDK_ROOT=$HOME/android-sdk
      - mkdir -p $ANDROID_SDK_ROOT
      - curl -s https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -o cmdline-tools.zip
      - unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
      - export PATH=$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
      - yes | sdkmanager --licenses || true
      - sdkmanager "platform-tools" "platforms;android-22" "build-tools;26.0.2"
      - echo "=== Android SDK setup complete ==="
      - chmod +x ./gradlew

  pre_build:
    commands:
      - echo "=== Cleaning project ==="
      - ./gradlew clean --stacktrace --info

  build:
    commands:
      - echo "=== Building APK and test APK ==="
      - ./gradlew assembleDebug assembleAndroidTest --stacktrace --info

  post_build:
    commands:
      - echo "=== Listing generated APKs ==="
      - find app/build/outputs -name "*.apk"

artifacts:
  files:
    - app/build/outputs/**/*.apk
