version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "=== Installing Gradle 7.6.1 ==="
      - |
        for i in 1 2 3; do
          curl -L --fail --retry 3 --retry-delay 5 https://services.gradle.org/distributions/gradle-7.6.1-bin.zip -o gradle.zip && break
          echo "Retrying Gradle download ($i)..."
          sleep 5
        done
      - file gradle.zip | grep 'Zip archive data' || (echo "Gradle zip download failed or corrupted!" && exit 1)
      - unzip -q gradle.zip
      - export PATH=$PWD/gradle-7.6.1/bin:$PATH

      - echo "=== Installing Android SDK (Platform 22 + Build Tools 26.0.2) ==="
      - export ANDROID_SDK_ROOT=$HOME/android-sdk
      - mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
      - curl -s https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -o cmdline-tools.zip
      - unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/latest
      - export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
      - yes | sdkmanager --licenses || true
      - sdkmanager "platform-tools" "platforms;android-22" "build-tools;26.0.2"
      - echo "=== Android SDK setup complete ==="
      - chmod +x ./gradlew

  pre_build:
    commands:
      - echo "=== Cleaning project ==="
      - ./gradlew clean --stacktrace --info

  build:
    commands:
      - echo "=== Building APK and test APK ==="
      - ./gradlew assembleDebug assembleAndroidTest --stacktrace --info

  post_build:
    commands:
      - echo "=== Listing generated APKs ==="
      - find app/build/outputs -name "*.apk"

artifacts:
  files:
    - app/build/outputs/**/*.apk
