version: 0.2

env:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx2g"
    _JAVA_OPTIONS: "-Xmx2g"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - set -e
      - echo "=== Installing Gradle 7.6.1 ==="
      - |
        for a in 1 2 3; do
          curl -fsSL --retry 3 --retry-delay 5 \
            https://services.gradle.org/distributions/gradle-7.6.1-bin.zip \
            -o gradle.zip && break
          echo "Gradle download retry $a failed – retrying…"
        done
      - file gradle.zip | grep -q 'Zip archive data' || { echo "❌ Gradle ZIP corrupt"; exit 1; }
      - unzip -q gradle.zip
      - export PATH="$PWD/gradle-7.6.1/bin:$PATH"
      - gradle --version

      - echo "=== Installing Android SDK CLI tools ==="
      - export ANDROID_SDK_ROOT="$HOME/android-sdk"
      - mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
      - curl -fsSL https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -o cmdline-tools.zip
      - unzip -q cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools/tmp"
      - mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
      - mv "$ANDROID_SDK_ROOT/cmdline-tools/tmp"/* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
      - rm -rf "$ANDROID_SDK_ROOT/cmdline-tools/tmp"
      - export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
      - sdkmanager --version || { echo "❌ sdkmanager missing"; exit 1; }
      - yes | sdkmanager --licenses >/dev/null
      - sdkmanager "platform-tools" "platforms;android-29" "build-tools;33.0.2"
      - echo "=== Android SDK ready ==="
      - chmod +x ./gradlew

  pre_build:
    commands:
      - echo "=== Gradle clean ==="
      - ./gradlew clean --stacktrace --info

  build:
    commands:
      - echo "=== Gradle assemble ==="
      - ./gradlew assembleDebug assembleAndroidTest --stacktrace --info

  post_build:
    commands:
      - echo "=== APKs generated ==="
      - find app/build/outputs -name "*.apk" -print
      - |
        if [ $(find app/build/outputs -name "*.apk" | wc -l) -eq 0 ]; then
          echo "❌ No APKs produced – failing build"; exit 1; fi

artifacts:
  discard-paths: yes
  files:
    - app/build/outputs/**/*.apk

cache:
  paths:
    - '/root/.gradle/**/*'
    - '$HOME/android-sdk/**/*'
