---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Android App Pipeline: GitHub -> CodeBuild -> Device Farm'

Parameters:
  # *** This value must always be passed in when creating / updating stack
  # "NoEcho" is set to true, for security, so token won't be visible when examining the resulting stack
  GitHubOAuthToken:
    Type: String
    NoEcho: true
    MinLength: 40
    MaxLength: 40
    AllowedPattern: '[a-z0-9]*'

  GitHubOwner:
    Type: String
    Default: mikeapted
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubRepo:
    Type: String
    Default: aws-codepipeline-devicefarm
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubBranch:
    Type: String
    Default: master
    AllowedPattern: "[A-Za-z0-9-]+"

  DeviceFarmProjectId:
    Type: String
    Default: a5e16b3e-fe5a-4d50-8c1e-d6d2e1d21c88
    AllowedPattern: "[A-Za-z0-9-]+"

  DevicePoolArn:
    Type: String
    Default: arn:aws:devicefarm:us-west-2::devicepool:082d10e5-d7d7-48a5-ba5c-b33d66efa1f5
    AllowedPattern: "[A-Za-z0-9-:]+"

  TestType:
    Type: String
    Default: BUILTIN_FUZZ
    AllowedValues: 
      - BUILTIN_FUZZ
      - BUILTIN_EXPLORER
      - APPIUM_JAVA_TESTNG

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "GitHub Configuration"
        Parameters: 
          - GitHubOwner
          - GitHubRepo
          - GitHubBranch
          - GitHubOAuthToken
      - 
        Label: 
          default: "Device Farm Configuration"
        Parameters: 
          - DeviceFarmProjectId
          - DevicePoolArn
          - TestType
    ParameterLabels: 
      GitHubOwner: 
        default: "What is the name of the GitHub user?"
      GitHubRepo: 
        default: "What is the name of the GitHub repo?"
      GitHubBranch: 
        default: "What branch should be monitored by the pipeline for changes?"
      GitHubOAuthToken: 
        default: "What is the value of a valid GitHub personal token?"
      DeviceFarmProjectId: 
        default: "What Device Farm project ID should be used for testing?"
      DevicePoolArn:
        default: "What Device Farm device pool ARN should be used for testing?"
      TestType:
        default: "What test type should be used for testing?"

Conditions: 
  IsAppiumTest: !Equals [ !Ref TestType, "APPIUM_NODE" ]

Resources:
  ArtifactsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Location: !Ref 'ArtifactsBucket'
        Type: S3
      Description: !Join
        - ''
        - - 'CodeBuild Project for '
          - !Ref 'AWS::StackName'
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:1.0
        Type: LINUX_CONTAINER
      Name: !Ref 'AWS::StackName'
      ServiceRole: !Ref 'PipelineRole'
      Source:
        Type: CODEPIPELINE      

  Pipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      Name: !Ref 'AWS::StackName'
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt 'PipelineRole.Arn'
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Provider: GitHub
            Version: 1
          Configuration:
            Owner: !Ref GitHubOwner
            Repo: !Ref GitHubRepo
            Branch: !Ref GitHubBranch
            PollForSourceChanges: false
            OAuthToken: !Ref GitHubOAuthToken
          InputArtifacts: []
          OutputArtifacts:
          - Name: SourceArtifact
          RunOrder: 1
      - Name: Build
        Actions:
        - ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: 1
          Configuration:
            ProjectName: !Ref 'AWS::StackName'
          InputArtifacts:
          - Name: SourceArtifact
          Name: Build
          OutputArtifacts:
          - Name: BuildArtifact
          RunOrder: 1
      - Name: Test
        Actions:
        - ActionTypeId:
            Category: Test
            Owner: AWS
            Provider: DeviceFarm
            Version: 1
          Configuration:
            RecordAppPerformanceData: true
            AppType: Android
            ProjectId: !Ref DeviceFarmProjectId
            App: app-debug.apk
            DevicePoolArn: !Ref DevicePoolArn
            TestType: !Ref TestType
            Test: !If [IsAppiumTest, "zip-with-dependencies.zip", !Ref "AWS::NoValue"]
          InputArtifacts:
          - Name: BuildArtifact
          Name: Test
          RunOrder: 1

  GithubWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubOAuthToken
      RegisterWithThirdParty: 'true'
      Filters:
      - JsonPath: "$.ref"
        MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref Pipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt Pipeline.Version

  PipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'codepipeline.amazonaws.com'
            - 'codebuild.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AdministratorAccess'